[package]
name = "vbr-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8"
atomic = "0.5"
portable-atomic = "1"
arrayvec = "0.7.4"
